{%- if values.componentName %}
  {%- set name = values.componentName %}
{%- else %}
  {%- set name = values.repoName %}
{% endif -%}

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ name }}
  description: |
    Fruit backend component.
  annotations:
    github.com/project-slug: open-demo-2024/${{ name }}
    backstage.io/techdocs-ref: dir:.
    quay.io/repository-slug: rh_ee_symartin/${{ name }}
spec:
  type: library
  owner: user:smartinus44
  lifecycle: experimental
